include:
  - local: 'pitstop-customer/.gitlab-ci.yml'
  - local: 'pitstop-vehicle/.gitlab-ci.yml'
  - local: 'pitstop-workshop-planning/.gitlab-ci.yml'
  - local: 'pitstop-express-gateway/.gitlab-ci.yml'
  - local: 'pitstop-webapp/.gitlab-ci.yml'