include:
  - local: '.gitlab-ci-base.yml'
variables:
  SERVICE_PATH: pitstop-vehicle
  DOCKER_IMAGE_NAME: pitstop-vehicle
  ARTIFACTS_PATH: node_modules/
  SECURITY_JOB: pitstop-vehicle-security-scan
  
stages:
  - security
  - build
  - package
pitstop-vehicle-security-scan:
  extends: .security_scan
  
build-vehicle-service:
  stage: build
  image: node:16
  needs:
    - pitstop-vehicle-security-scan
  script:
    - cd ${SERVICE_PATH}
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CACHE_KEY}-node
    paths:
      - ${SERVICE_PATH}/.npm/
      - ${SERVICE_PATH}/node_modules/
    policy: pull-push

package-vehicle-service:
  extends: .package