image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: pitstop-vehicle
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - build
  - package
  - publish 

build:
  image: node:18-alpine
  stage: build
  script:
    - echo "Building the application-----------------------------------------"
    - npm install  
    - echo "Build completed --------------------------------------------------"
  artifacts:
    paths:
      - dist/
  cache:
    paths:
      - node_modules/

package:
  stage: package
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $CI_REGISTRY_USER/$IMAGE_NAME:latest

publish:
  stage: publish
  script:
    - echo "Logging into GitLab registry-------------------------------------"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:latest