stages:
  - build
  - package
  - publish

build:
  stage: build
  image: node:10
  script:
    - echo "Installing dependencies for vehicle service"
    - npm install --production=false
    - echo "Dependencies installed successfully"
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
      - package*.json

package:
  stage: package
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - echo "Building Docker image for vehicle service"
    - docker build -t "$CI_REGISTRY_USER/pitstop-vehicle:$CI_COMMIT_REF_NAME" ./pitstop-vehicle

publish:
  stage: publish
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "Logging into GitLab registry"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push "$CI_REGISTRY_USER/pitstop-vehicle:$CI_COMMIT_REF_NAME"