include:
  - local: '.gitlab-ci-base.yml'
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: DAST.gitlab-ci.yml

variables:
  GITLAB_ADVANCED_SAST_ENABLED: 'true'
  SERVICE_PATH: pitstop-webapp
  DOCKER_IMAGE_NAME: pitstop-webapp
  ARTIFACTS_PATH: dist/
  BUILD_COMMAND: build
  SECURITY_JOB: webapp-security-scan
  NODE_ENV: production
  CACHE_KEY: ${CI_COMMIT_REF_SLUG}
  NODE_VERSION: "10"
  YAML_NAME  : "frontend.yaml"
  DAST_AUTO_UPDATE_ADDONS: "true"
  CS_IMAGE : $CI_REGISTRY_USER/${DOCKER_IMAGE_NAME}:latest
  DAST_FULL_SCAN_ENABLED: 'true'
  DAST_WEBSITE: "http://localhost:8080"

stages:
  - security
  - test 
  - build
  - package
  - deploy-k8s

.node_cache_template: &node_cache
  cache:
    key: ${CACHE_KEY}-node
    paths:
      - pitstop-webapp/.npm/
      - pitstop-webapp/node_modules/
    policy: pull-push


gemnasium-dependency_scanning:
  tags:
    - pitstop-docker
  rules:
    - when: always


dast:
  variables:
    DAST_TARGET_URL: "http://localhost:8080"
  stage: .post
  services:
    - name: $CS_IMAGE
      alias: pitstop-webapp
  rules:
    - when: always




webapp-security-scan:
  extends: .security_scan

container_scanning:
  tags:
    - pitstop-docker
  stage: container-security
  rules:
    - when: always


build-webapp-service:
  stage: build
  image: node:10
  # needs:
  #   - webapp-security-scan
  script:
    - cd pitstop-webapp
    - npm install --production=false
    - npm run build
  artifacts:
    paths:
      - pitstop-webapp/dist/
  cache:
      paths:
          - pitstop-webapp/node_modules/


package-webapp:
  extends: .package
  needs:
    - build-webapp-service
  variables:
    SERVICE_PATH: ${SERVICE_PATH}

deploy-k8s-service:
    image: bitnami/git:latest
    stage: deploy-k8s
    before_script:
      - git config --global user.email "zoulatizakaria3@gmail.com"
      - git config --global user.name "Zakaria-Zoulati"
      - git config --global credential.helper cache
    script:
      - git clone https://gitlab.com/Zakaria-Zoulati/devops_k8s.git
      - cd devops_k8s/pitstop-k8s/
      - cat frontend.yaml
      - COMMIT_HASH=$(echo "$CI_COMMIT_SHA" | cut -c1-8)
      - | 
        sed -i "s|image: slihatim/pitstop-webapp\(:.*\)\?|image: slihatim/pitstop-webapp:${COMMIT_HASH}|" frontend.yaml
      - cat frontend.yaml
      - git add ${YAML_NAME}
      - git commit -m "microservice manifests versions changes successfully"
      # - git remote add origin https://oauth2:$ACCESS_TOKEN_REPO@gitlab.com/Zakaria-Zoulati/devops_k8s.git
      # - git push -u origin main
      - echo $ACCESS_TOKEN_REPO
      - git remote set-url origin https://oauth2:$ACCESS_TOKEN_REPO@gitlab.com/Zakaria-Zoulati/devops_k8s.git
      - git push origin main 



