stages:
  - build
  - security
  - package

variables:
  NODE_ENV: production

build-webapp-service:
  stage: build
  image: node:10
  script:
    - cd pitstop-webapp
    - npm install --production=false
    - npm run build
  artifacts:
    paths:
      - pitstop-webapp/dist/
  cache:
      paths:
          - pitstop-webapp/node_modules/
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "devSecOps" || $CI_PIPELINE_SOURCE == "merge_request_event"

security-scan:
  stage: security
  image: aquasec/trivy:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "devSecOps"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
  script:
    - trivy filesystem --format json -o trivy-report.json --severity HIGH,CRITICAL ./pitstop-webapp
  artifacts:
    paths:
      - trivy-report.json
    expire_in: 1 week

package-webapp-service:
  stage: package
  image: docker:24
  services:
    - docker:24-dind
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t "$CI_REGISTRY_USER/pitstop-webapp:$CI_COMMIT_SHA" -t "$CI_REGISTRY_USER/pitstop-webapp:latest" ./pitstop-webapp
    - docker push "$CI_REGISTRY_USER/pitstop-webapp:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_USER/pitstop-webapp:latest"
