stages:
  - build
  - package

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build-workshop-planning:
  stage: build
  image: node:10
  script:
    - echo "Installing dependencies for vehicle service"
    - cd ./pitstop-workshop-planning
    - npm install --production=false
    - echo "Dependencies installed successfully"
  cache:
    paths:
      - pitstop-workshop-planning/node_modules/
  artifacts:
    paths:
      - pitstop-workshop-planning/node_modules/
      - pitstop-workshop-planning/package*.json

package-workshop-planning:
  stage: package
  image: docker:24
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  services:
    - name: docker:24-dind
      alias: docker
      command: ["--tls=false", "--tls-verify=false", "--host=unix:///var/run/docker.sock", "--host=tcp://0.0.0.0:2375"]
  before_script:
    - sleep 10  # Give Docker time to start
    - docker info  # Verify Docker connection
  script:
    - echo "Building and pushing vehicle service Docker image"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t "$CI_REGISTRY_USER/pitstop-workshop-planning:$CI_COMMIT_REF_NAME" ./pitstop-workshop-planning
    - docker push "$CI_REGISTRY_USER/pitstop-workshop-planning:$CI_COMMIT_REF_NAME"