include:
  - local: '.gitlab-ci-base.yml'
variables:
  SERVICE_PATH: pitstop-workshop-planning
  DOCKER_IMAGE_NAME: pitstop-workshop-planning
  ARTIFACTS_PATH: node_modules/
  SECURITY_JOB: workshop-planning-security-scan
stages:
  - security
  - build
  - package
workshop-planning-security-scan:
  extends: .security_scan

build-workshop-planning:
  stage: build
  image: node:16
  needs:
    - workshop-planning-security-scan
  script:
    - cd ${SERVICE_PATH}
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CACHE_KEY}-node
    paths:
      - ${SERVICE_PATH}/.npm/
      - ${SERVICE_PATH}/node_modules/
    policy: pull-push

package-workshop-planning:
  extends: .package