stages:
  - build
  - package

build-workshop-planning:
  stage: build
  image: node:10
  script:
    - echo "Installing dependencies for workshop planning service"
    - cd ./pitstop-workshop-planning
    - npm install --production=false
    - echo "Dependencies installed successfully"
  cache:
    paths:
      - pitstop-workshop-planning/node_modules/
  artifacts:
    paths:
      - pitstop-workshop-planning/node_modules/
      - pitstop-workshop-planning/package*.json

package-workshop-planning:
  stage: package
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "Building and pushing workshop planning service Docker image"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t "$CI_REGISTRY_USER/pitstop-workshop-planning:$CI_COMMIT_REF_NAME" ./pitstop-workshop-planning
    - docker push "$CI_REGISTRY_USER/pitstop-workshop-planning:$CI_COMMIT_REF_NAME"