apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rabbitmq-pdb
  namespace: pitstop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: rabbitmq

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customer-service-pdb
  namespace: pitstop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: customer-service

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vehicle-service-pdb
  namespace: pitstop
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: vehicle-service