gitlabUrl: https://gitlab.com/
runnerRegistrationToken: "glrt-t3_t9iFyq3UythTsTyT9zzp"

serviceAccount:
  name: gitlab-runner
  create: false

rbac:
  create: false

runners:
  executor: kubernetes
  tags: ["devops"]
  config: |
    [[runners]]
      name = "k8s-runner"
      output_limit = 4096
      [runners.kubernetes]
        namespace = "gitlab-runner"
        image = "ubuntu:20.04"
        privileged = true
        service_account = "gitlab-runner"
        cpu_request = "250m"
        cpu_limit = "500m"
        memory_request = "256Mi"
        memory_limit = "512Mi"
        helper_cpu_request = "250m"
        helper_cpu_limit = "500m"
        helper_memory_request = "256Mi"
        helper_memory_limit = "512Mi"
        poll_timeout = 600
        poll_interval = 5
        concurrent = 10
        check_interval = 30