include:
  - local: '.gitlab-ci-base.yml'

variables:
  SERVICE_PATH: pitstop-express-gateway
  DOCKER_IMAGE_NAME: pitstop-express-gateway
  NODE_ENV: production
  CACHE_KEY: ${CI_COMMIT_REF_SLUG}

stages:
  - security
  - build
  - package

express-gateway-security-scan:
  extends: .security_scan

build-express-gateway-service:
  stage: build
  image: node:16
  needs:
    - express-gateway-security-scan
  script:
    - cd ${SERVICE_PATH}
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CACHE_KEY}-node
    paths:
      - ${SERVICE_PATH}/.npm/
      - ${SERVICE_PATH}/node_modules/
    policy: pull-push

package-express-gateway-service:
  extends: .package