stages:
  - build
  - security
  - package

variables:
  NODE_ENV: production

build-express-gateway-service:
  stage: build
  image: node:10
  script:
    - echo "Installing dependencies for gate-way service"
    - cd ./pitstop-express-gateway
    - npm install --production=false
    - echo "Dependencies installed successfully"
  cache:
    paths:
      - pitstop-express-gateway/node_modules
  artifacts:
    paths:
      - pitstop-express-gateway/node_modules
      - pitstop-express-gateway/package*.json
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE != "merge_request_event"'
      when: always
    - when: never

gateway-security-scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "devSecOps"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never
  script:
    - trivy fs --format json -o trivy-report.json --severity HIGH,CRITICAL ./pitstop-express-gateway
  artifacts:
    paths:
      - trivy-report.json
    expire_in: 1 week

package-express-gateway-service:
  stage: package
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "Building and pushing gateway service docker image"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t "$CI_REGISTRY_USER/pitstop-gateway:$CI_COMMIT_REF_NAME" ./pitstop-express-gateway
    - docker push "$CI_REGISTRY_USER/pitstop-gateway:$CI_COMMIT_REF_NAME"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - pitstop-express-gateway/**
      when: always
    - when: never