stages:
  - build
  - package

# Stage 1: Build the Node.js application
build-customer-service:
  stage: build
  image: node:10
  script:
    - cd ./pitstop-customer
    - npm install --production=false
  cache:
      paths:
        - pitstop-customer/node_modules/
        - pitstop-customer/package*.json
# Stage 2: Package the application into a Docker image
package-customer-service:
  stage: package
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t "$CI_REGISTRY_USER/pitstop-customer:$CI_COMMIT_REF_NAME" -t "$CI_REGISTRY_USER/pitstop-customer:latest" ./pitstop-customer
    - docker push "$CI_REGISTRY_USER/pitstop-customer:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_USER/pitstop-customer:latest"
