stages:
  - build
  - security
  - package

variables:
  NODE_ENV: production

# Stage 1: Build the Node.js application
build-customer-service:
  stage: build
  image: node:10
  script:
    - cd ./pitstop-customer
    - npm install --production=false
  cache:
      paths:
        - pitstop-customer/node_modules/
        - pitstop-customer/package*.json
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "devSecOps"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

pitstop-customer-security-scan:
  stage: security
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "devSecOps"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - when: never
  script:
    - trivy fs --format json -o trivy-report.json --severity HIGH,CRITICAL  ./pitstop-customer
  artifacts:
    paths:
      - trivy-report.json
    expire_in: 1 week

# Stage 2: Package the application into a Docker image
package-customer-service:
  stage: package
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - docker build -t "$CI_REGISTRY_USER/pitstop-customer:$CI_COMMIT_REF_NAME" -t "$CI_REGISTRY_USER/pitstop-customer:latest" ./pitstop-customer
    - docker push "$CI_REGISTRY_USER/pitstop-customer:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_USER/pitstop-customer:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      changes:
        - pitstop-customer/**
      when: always
    - when: never
