include:
  - local: '.gitlab-ci-base.yml'

variables:
  SERVICE_PATH: pitstop-customer
  DOCKER_IMAGE_NAME: pitstop-customer
  ARTIFACTS_PATH: node_modules/
  SECURITY_JOB: pitstop-customer-security-scan

stages:
  - security
  - build
  - package

pitstop-customer-security-scan:
  extends: .security_scan

build-customer-service:
  stage: build
  image: node:16
  needs:
    - pitstop-customer-security-scan
  script:
    - cd ${SERVICE_PATH}
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CACHE_KEY}-node
    paths:
      - ${SERVICE_PATH}/.npm/
      - ${SERVICE_PATH}/node_modules/
    policy: pull-push

package-customer-service:
  extends: .package